# This deliverately is not "python" as a work-around to support
# multi-os builds with custom Python versions in Travis CI.
language: cpp

os:
  - linux

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - PYTHON_EXE=python$TRAVIS_PYTHON_VERSION ./setup.py install --user

script:
  - PYTHON_EXE=python$TRAVIS_PYTHON_VERSION ./setup.py test
